//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolEasy.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseMaster()
        {
            this.ClassMasters = new HashSet<ClassMaster>();
            this.RegistrationAmountMasters = new HashSet<RegistrationAmountMaster>();
            this.RegistrationMasters = new HashSet<RegistrationMaster>();
        }
    
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string SchoolCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassMaster> ClassMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationAmountMaster> RegistrationAmountMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationMaster> RegistrationMasters { get; set; }
    }
}
