//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolEasy.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationAmountMaster
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string SchoolCode { get; set; }
        public decimal RegistrationAmount { get; set; }
    
        public virtual CourseMaster CourseMaster { get; set; }
    }
}
