//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolEasy.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationMaster
    {
        public int RegistrationId { get; set; }
        public string RegistrationNo { get; set; }
        public int CourseId { get; set; }
        public int ClassId { get; set; }
        public string StudentName { get; set; }
        public string FatherName { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string SchoolCode { get; set; }
        public Nullable<decimal> RegistrationAmount { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public bool Active { get; set; }
    
        public virtual ClassMaster ClassMaster { get; set; }
        public virtual CourseMaster CourseMaster { get; set; }
    }
}
