//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolEasy.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolAppEntities : DbContext
    {
        public SchoolAppEntities()
            : base("name=SchoolAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Login> tb_Login { get; set; }
        public virtual DbSet<tb_SchoolRegister> tb_SchoolRegister { get; set; }
        public virtual DbSet<ClassMaster> ClassMasters { get; set; }
        public virtual DbSet<CourseMaster> CourseMasters { get; set; }
        public virtual DbSet<SectionMaster> SectionMasters { get; set; }
        public virtual DbSet<RegistrationAmountMaster> RegistrationAmountMasters { get; set; }
        public virtual DbSet<RegistrationMaster> RegistrationMasters { get; set; }
    }
}
