//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolEasy.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionMaster
    {
        public int SectionId { get; set; }
        public int ClassId { get; set; }
        public string SectionName { get; set; }
        public string SchoolCode { get; set; }
    
        public virtual ClassMaster ClassMaster { get; set; }
    }
}
